"""
Module: services/memory.py

PURPOSE:
    Multi-turn conversation memory backed by Amazon DynamoDB. Without this module,
    every user query is completely stateless — the agent has no context from prior
    turns. This module allows the agent to answer follow-up questions like
    "Can you apply that rule to a compressor station?" where "that rule" refers to
    something from a previous turn.

ARCHITECTURE POSITION:

    User Query (turn N)
         │
         ▼
    chat.py endpoint
         │
         ├─► DynamoDBMemoryManager.get_history(session_id)
         │       Returns last N turns as formatted string
         │
         ▼
    FullPipelineCrew.kickoff(inputs={..., "conversation_history": ...})
         │
         ▼
    Agents see prior context in their task descriptions
         │
         ▼
    DynamoDBMemoryManager.add_turn(session_id, "assistant", answer)
         │
         ▼
    Response returned to user

DYNAMODB SCHEMA:
    Table: gas-energy-copilot-conversations (created by terraform/main.tf)
    Hash key:  session_id (String) — UUID per chat session, generated by client or API
    Range key: turn_id    (String) — Zero-padded integer "0001", "0002", ...

    Why composite key (Hash + Range):
      A DynamoDB Query on hash key alone returns all turns for a session in one
      round trip (very efficient). The zero-padded range key ensures turns are
      returned in chronological order (DynamoDB sorts range keys lexicographically).

    Item attributes:
      - role      (S): "user" | "assistant"
      - content   (S): message text
      - timestamp (S): ISO8601 UTC timestamp
      - metadata  (M): agent name, retrieval scores, router decision, etc.
      - ttl       (N): Unix epoch seconds — DynamoDB auto-deletes after this time

LIBRARY CHOICE — boto3 (DynamoDB):
    Why boto3 DynamoDB over alternatives:
      - vs aiobotocore: We intentionally use synchronous boto3 here. CrewAI is
        synchronous (it runs in a ThreadPoolExecutor inside FastAPI's async handler).
        Mixing asyncio and threads with aiobotocore adds complexity without benefit.
      - vs dynamodb-json: thin wrapper that adds a dependency; boto3's TypeDeserializer
        is standard and sufficient for our flat schema.
      - vs pynamodb: ORM layer that's useful for complex schemas; overkill for our
        simple key-value chat log.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any

import boto3
from boto3.dynamodb.conditions import Key
from botocore.exceptions import ClientError, NoCredentialsError

from gas_energy_copilot.ai_copilot.core.config import app_config

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ConversationTurn:
    """
    A single message in a conversation.

    This is the canonical in-memory representation. It is serialised to/from
    DynamoDB items by the DynamoDBMemoryManager methods below.

    Attributes:
        session_id: UUID identifying the chat session (DynamoDB Hash key).
        turn_id:    Zero-padded sequential number, e.g. "0001" (Range key).
        role:       "user" for human messages, "assistant" for agent replies.
        content:    The raw message text.
        timestamp:  UTC ISO8601 timestamp of when the turn was stored.
        metadata:   Free-form dict for extra data (agent name, retrieval scores,
                    router decision, judge confidence, etc.).
    """

    session_id: str
    turn_id: str
    role: str           # "user" | "assistant"
    content: str
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dynamodb_item(self, ttl_seconds: int) -> dict[str, Any]:
        """
        Serialise this turn to a DynamoDB PutItem-compatible dict.

        DynamoDB requires all numeric values to be Decimal, but for simple integers
        like `ttl` we pass them as integers and let boto3 handle the conversion.

        Args:
            ttl_seconds: Unix epoch seconds at which DynamoDB should auto-delete this item.

        Returns:
            Dict with string/numeric/map values suitable for DynamoDB PutItem.
        """
        return {
            "session_id": self.session_id,
            "turn_id": self.turn_id,
            "role": self.role,
            "content": self.content,
            "timestamp": self.timestamp,
            "metadata": self.metadata or {},  # DynamoDB rejects None for Map type
            "ttl": ttl_seconds,
        }

    @classmethod
    def from_dynamodb_item(cls, item: dict[str, Any]) -> "ConversationTurn":
        """
        Deserialise a DynamoDB item dict to a ConversationTurn.

        DynamoDB Query returns items as plain Python dicts (boto3 resource API
        auto-deserialises types; client API would need TypeDeserializer).
        We use the resource API, so this is straightforward attribute extraction.

        Args:
            item: Raw dict from DynamoDB Query response.

        Returns:
            ConversationTurn instance.
        """
        return cls(
            session_id=item["session_id"],
            turn_id=item["turn_id"],
            role=item["role"],
            content=item["content"],
            timestamp=item.get("timestamp", ""),
            metadata=item.get("metadata", {}),
        )


# ---------------------------------------------------------------------------
# Memory manager
# ---------------------------------------------------------------------------


class DynamoDBMemoryManager:
    """
    Manages multi-turn conversation history in Amazon DynamoDB.

    This is the central memory component. It provides four operations:
      1. get_history  — load the last N turns for a session
      2. add_turn     — append a new turn to a session
      3. clear_session — delete all turns for a session (used in tests / "clear chat")
      4. format_as_context — format turns as a string for injection into prompts

    USAGE PATTERN:
        memory = DynamoDBMemoryManager()

        # At the start of a request: load history
        history = memory.get_history("session-abc-123")
        context_str = memory.format_as_context(history)

        # After getting the answer: persist both turns
        memory.add_turn("session-abc-123", "user", user_question)
        memory.add_turn("session-abc-123", "assistant", answer)

    GRACEFUL DEGRADATION:
        If DynamoDB is unreachable (e.g., local dev without AWS credentials),
        all operations log a warning and return empty results rather than
        crashing. The chat system continues working — just without memory.

        To disable memory entirely, set [app.memory] enabled = false in settings.toml.
        The chat endpoint checks this flag and skips memory calls.

    LAZY INITIALISATION:
        The boto3 DynamoDB resource is created on first use, not at import time.
        This avoids import-time failures when running tests without AWS credentials,
        and prevents unnecessary connection overhead for routes that don't use memory.
    """

    def __init__(self) -> None:
        config = app_config()
        self._config = config.memory
        self._table_name = config.memory.table_name
        self._region = config.memory.region
        self._max_turns = config.memory.max_turns
        self._ttl_days = config.memory.ttl_days

        # Lazy init: _table is None until first use
        self._table = None

    def _get_table(self):
        """
        Lazily initialise the DynamoDB table resource.

        We use the boto3 *resource* API (higher-level) rather than the *client*
        API (lower-level) because the resource API automatically deserialises
        DynamoDB types (S, N, M, L) to Python primitives — no manual TypeDeserializer.

        The resource is thread-safe: boto3 manages connection pooling internally.
        The DynamoDB Table object is created once and reused for all operations.

        Returns:
            boto3 DynamoDB Table resource, or None if connection failed.
        """
        if self._table is not None:
            return self._table

        try:
            dynamodb = boto3.resource("dynamodb", region_name=self._region)
            self._table = dynamodb.Table(self._table_name)
            log.debug("DynamoDB table resource initialised", extra={"table": self._table_name})
        except (NoCredentialsError, Exception) as e:
            log.warning(
                "DynamoDB connection failed — memory disabled for this instance. "
                "Set [app.memory] enabled=false to suppress this warning.",
                exc_info=e,
            )
        return self._table

    def get_history(self, session_id: str) -> list[ConversationTurn]:
        """
        Retrieve the most recent conversation turns for a session.

        Queries DynamoDB with a KeyConditionExpression on the Hash key (session_id).
        DynamoDB returns items sorted by Range key (turn_id) — which is chronological
        because turn_ids are zero-padded integers ("0001", "0002", ...).

        We fetch the last `max_turns` items by scanning from the end using
        ScanIndexForward=False (descending order) then reversing in Python.
        This is more efficient than fetching all items and slicing.

        Args:
            session_id: UUID identifying the chat session.

        Returns:
            List of ConversationTurn objects in chronological order (oldest first),
            limited to max_turns. Returns empty list on error or if no history exists.

        Example:
            history = memory.get_history("session-abc-123")
            for turn in history:
                print(f"{turn.role}: {turn.content[:80]}")
        """
        table = self._get_table()
        if table is None:
            return []

        try:
            response = table.query(
                KeyConditionExpression=Key("session_id").eq(session_id),
                ScanIndexForward=False,  # descending → newest first
                Limit=self._max_turns,
            )
            items = response.get("Items", [])
            # Reverse to restore chronological order (oldest first)
            turns = [ConversationTurn.from_dynamodb_item(item) for item in reversed(items)]
            log.debug("Loaded conversation history", extra={"session_id": session_id, "turns": len(turns)})
            return turns
        except ClientError as e:
            log.warning("DynamoDB get_history failed", extra={"error": str(e), "session_id": session_id})
            return []

    def add_turn(
        self,
        session_id: str,
        role: str,
        content: str,
        metadata: dict[str, Any] | None = None,
    ) -> bool:
        """
        Append a new conversation turn to DynamoDB.

        Determines the next turn_id by counting existing turns for the session,
        then puts a new item with the appropriate TTL for auto-expiry.

        Turn ID Generation:
            We use a count query (Select='COUNT') to find the current number of turns,
            then increment by 1 and zero-pad to 4 digits. This is a simple approach
            that works correctly for sessions with ≤9999 turns (sufficient for chat).
            A more robust approach would use a conditional write with version numbers,
            but that adds latency and complexity for negligible benefit.

        Args:
            session_id: UUID identifying the chat session.
            role:       "user" | "assistant"
            content:    The message text.
            metadata:   Optional dict with extra data (agent name, scores, etc.).

        Returns:
            True if the turn was stored successfully, False on error.

        Example:
            memory.add_turn("session-abc-123", "user", "What is MAOP under §192.619?")
            memory.add_turn("session-abc-123", "assistant", "MAOP is the Maximum...",
                            metadata={"judge_confidence": 0.92, "query_type": "regulatory_lookup"})
        """
        table = self._get_table()
        if table is None:
            return False

        try:
            # Get the current turn count to determine the next turn_id
            count_response = table.query(
                KeyConditionExpression=Key("session_id").eq(session_id),
                Select="COUNT",
            )
            next_turn_number = count_response.get("Count", 0) + 1
            turn_id = f"{next_turn_number:04d}"  # e.g., "0001", "0042"

            # TTL: Unix epoch seconds N days from now
            ttl_seconds = int(time.time()) + (self._ttl_days * 86400)

            turn = ConversationTurn(
                session_id=session_id,
                turn_id=turn_id,
                role=role,
                content=content,
                metadata=metadata or {},
            )
            table.put_item(Item=turn.to_dynamodb_item(ttl_seconds))
            log.debug("Stored conversation turn", extra={"session_id": session_id, "turn_id": turn_id, "role": role})
            return True
        except ClientError as e:
            log.warning("DynamoDB add_turn failed", extra={"error": str(e), "session_id": session_id})
            return False

    def clear_session(self, session_id: str) -> int:
        """
        Delete all turns for a session (used by "Clear Chat" button in Streamlit UI).

        DynamoDB does not support bulk deletes; we must query then delete item by item.
        For typical session sizes (≤50 turns) this is fine. For larger sessions,
        a batch_writer would be more efficient.

        Args:
            session_id: UUID identifying the chat session to clear.

        Returns:
            Number of turns deleted, or 0 on error.

        Example:
            n = memory.clear_session("session-abc-123")
            print(f"Cleared {n} turns")
        """
        table = self._get_table()
        if table is None:
            return 0

        try:
            response = table.query(
                KeyConditionExpression=Key("session_id").eq(session_id),
                ProjectionExpression="session_id, turn_id",  # only fetch keys, not content
            )
            items = response.get("Items", [])

            # Use batch_writer for efficient deletes (up to 25 per batch internally)
            with table.batch_writer() as batch:
                for item in items:
                    batch.delete_item(Key={"session_id": item["session_id"], "turn_id": item["turn_id"]})

            log.info("Cleared conversation session", extra={"session_id": session_id, "turns_deleted": len(items)})
            return len(items)
        except ClientError as e:
            log.warning("DynamoDB clear_session failed", extra={"error": str(e), "session_id": session_id})
            return 0

    def format_as_context(self, turns: list[ConversationTurn]) -> str:
        """
        Format a list of conversation turns as a prompt-injectable context string.

        The format is a simple chat log that LLMs understand universally:

            CONVERSATION HISTORY:
            User: <message>
            Assistant: <message>
            User: <message>

        This is intentionally simple — we avoid XML or JSON formats because:
          - Simple text is more readable in agent backstory/task descriptions.
          - LLMs handle "User:/Assistant:" prefixes reliably across all models.
          - JSON escaping would add noise for regulatory text with many special chars.

        Args:
            turns: List of ConversationTurn objects (chronological order).

        Returns:
            Formatted string suitable for injection into an agent task description.
            Returns empty string if turns is empty (no history available).

        Example:
            history = memory.get_history("session-abc-123")
            context = memory.format_as_context(history)
            # → "CONVERSATION HISTORY:\\nUser: What is MAOP?\\nAssistant: MAOP is..."
        """
        if not turns:
            return ""

        lines = ["CONVERSATION HISTORY:"]
        for turn in turns:
            prefix = "User" if turn.role == "user" else "Assistant"
            # Truncate very long turns to avoid overwhelming the context window.
            # 500 chars ≈ 125 tokens — reasonable summary of a prior answer.
            content_preview = turn.content[:500] + ("..." if len(turn.content) > 500 else "")
            lines.append(f"{prefix}: {content_preview}")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Module-level singleton (lazy, created on first import that calls it)
# ---------------------------------------------------------------------------

_memory_manager: DynamoDBMemoryManager | None = None


def get_memory_manager() -> DynamoDBMemoryManager:
    """
    Return a module-level singleton DynamoDBMemoryManager.

    Using a singleton avoids creating multiple boto3 sessions. The manager
    lazily initialises its DynamoDB connection on first use, so importing
    this function has zero overhead.

    Returns:
        Shared DynamoDBMemoryManager instance.
    """
    global _memory_manager
    if _memory_manager is None:
        _memory_manager = DynamoDBMemoryManager()
    return _memory_manager
